scala_library(name = 'scala',
   dependencies = [
     '3rdparty/jvm/org/apache/lucene:lucene-core-4.10.2',
     '3rdparty/jvm/org/apache/lucene:lucene-analyzers-common-4.10.2',
     '3rdparty/jvm/org/apache/lucene:lucene-queryparser-4.10.2',
     'taste/jsoup/src/main/scala',
   ],
   sources = rglobs('*.scala'),
)
