jvm_binary(name = 'study',
    main = 'info.pot420.lucene.Lunar',
    dependencies = [
        'taste/lucene/src/main/scala',
    ]
)

jvm_binary(name = 'ask',
    main = 'info.pot420.lucene.Ask',
    dependencies = [
        'taste/lucene/src/main/scala',
    ]
)
