jvm_binary(name = 'idea',
    dependencies = [
        'taste/finagle:server',
        'taste/jsoup:spoon',
        'taste/lucene:study',
        'taste/lucene:ask',
        'taste/xml:eugene',
    ]
)
